DESCRIPTION = "Generic purpose C++ multi threaded library, C++ Tango and \
Epics modules, Qt components for control system graphical user interfaces"
HOMEPAGE = "https://github.com/ELETTRA-SincrotroneTrieste/cumbia-libs"
LICENSE = "GPL-3.0-only"

LIC_FILES_CHKSUM = "file://${COREBASE}/meta/files/common-licenses/GPL-3.0-only;md5=c79ff39f19dfec6d293b95dea7b07891"

SRCREV = "660f1e9e867169ce6b78771d82edbd473c33d197"
